# Generated by Django 3.0.7 on 2021-07-22 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210713_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 7, 22, 9, 59, 23, 159139, tzinfo=utc)),
        ),
    ]
