# Generated by Django 3.0.7 on 2021-07-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_newpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='user',
        ),
    ]
